Fixing motor runs on subsequent robot connections and after disconnect
bb-frc-workshops/wpilib-ws-robot pull request #2
Opened 2020-09-14 18:06 UTC by jpokornyiii

2020-09-14 18:22 UTC, jpokornyiii commented
Depends on: https://github.com/bb-frc-workshops/node-wpilib-ws/pull/1

2020-09-15 16:54 UTC, zhiquanyeo requested changes
Can you also bump the `node-wpilib-ws` version to the next minor version? (I'll publish it shortly)

2020-09-16 01:22 UTC, jpokornyiii commented
> Can you also bump the `node-wpilib-ws` version to the next minor version? (I'll publish it shortly)

Fixed disabled mode and bumped node-wpilib-ws version to 0.0.5.

2020-09-17 00:18 UTC, zhiquanyeo approved these changes

2020-09-17 00:18 UTC, merged